### ISSUE TITLE
TypeError: h5py objects cannot be pickled

### ISSUE THREAD

**Issue by BrightMoonStar** [Lifelong-Robot-Learning/LIBERO#19]
Hi~
When I set num_worker to a number greater than 0, the following error will appear. How to solve this problem? I know that num_worker=0 can run, but I want to further improve the running speed. Thank you very much！

```
[info] start training on task 0
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/a/Videos/bin/boot/LIBERO/libero/lifelong/main.py", line 223, in main
    s_fwd, l_fwd = algo.learn_one_task(
  File "/home/a/Videos/bin/boot/LIBERO/libero/lifelong/algos/base.py", line 175, in learn_one_task
    for (idx, data) in enumerate(train_dataloader):
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/a/anaconda3/envs/LIBERO/lib/python3.8/site-packages/h5py/_hl/base.py", line 368, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by Cranial-XIX** [comment]
Hi, could you please provide the full command to reproduce this error?

**Comment by BrightMoonStar** [comment]
The following is the complete information when set num_worker>0 in .yaml file , so I have to set num_worker=0 to make it run which also causes training efficiency  lower as a side effect.

```
(LIBERO) lyf@Precision-7920-Tower:~/Videos/bin/boot/LIBERO/libero$ export CUDA_VISIBLE_DEVICES=0 && export MUJOCO_EGL_DEVICE_ID=0 && python lifelong/main.py seed=0 benchmark_name=libero_object policy=bc_rnn_policy lifelong=base
{ 'bddl_folder': None,
  'benchmark_name': 'libero_object',
  'data': { 'action_scale': 1.0,
            'affine_translate': 4,
            'data_modality': ['image', 'proprio'],
            'frame_stack': 1,
            'img_h': 128,
            'img_w': 128,
            'max_word_len': 25,
            'num_kp': 64,
            'obs': { 'modality': { 'depth': [],
                                   'low_dim': [ 'gripper_states',
                                                'joint_states'],
                                   'rgb': [ 'agentview_rgb',
                                            'eye_in_hand_rgb']}},
            'obs_key_mapping': { 'agentview_rgb': 'agentview_image',
                                 'eye_in_hand_rgb': 'robot0_eye_in_hand_image',
                                 'gripper_states': 'robot0_gripper_qpos',
                                 'joint_states': 'robot0_joint_pos'},
            'seq_len': 10,
            'shuffle_task': False,
            'state_dim': None,
            'task_group_size': 1,
            'task_order_index': 0,
            'train_dataset_ratio': 0.8,
            'use_ee': False,
            'use_eye_in_hand': True,
            'use_gripper': True,
            'use_joint': True},
  'device': 'cuda',
  'eval': { 'batch_size': 48,
            'eval': True,
            'eval_every': 5,
            'load_path': '',
            'max_steps': 600,
            'n_eval': 20,
            'num_procs': 20,
            'num_workers': 0,
            'save_sim_states': False,
            'use_mp': True},
  'folder': None,
  'init_states_folder': None,
  'lifelong': {'algo': 'Sequential'},
  'load_previous_model': False,
  'policy': { 'color_aug': { 'network': 'BatchWiseImgColorJitterAug',
                             'network_kwargs': { 'brightness': 0.3,
                                                 'contrast': 0.3,
                                                 'epsilon': 0.1,
                                                 'hue': 0.3,
                                                 'input_shape': None,
                                                 'saturation': 0.3}},
              'image_embed_size': 64,
              'image_encoder': { 'network': 'ResnetEncoder',
                                 'network_kwargs': { 'freeze': False,
                                                     'language_fusion': 'film',
                                                     'no_stride': False,
                                                     'pretrained': False,
                                                     'remove_layer_num': 4}},
              'language_encoder': { 'network': 'MLPEncoder',
                                    'network_kwargs': { 'hidden_size': 128,
                                                        'input_size': 768,
                                                        'num_layers': 1,
                                                        'output_size': 128}},
              'policy_head': { 'loss_kwargs': {'loss_coef': 1.0},
                               'network': 'GMMHead',
                               'network_kwargs': { 'activation': 'softplus',
                                                   'hidden_size': 1024,
                                                   'low_eval_noise': False,
                                                   'min_std': 0.0001,
                                                   'num_layers': 2,
                                                   'num_modes': 5}},
              'policy_type': 'BCRNNPolicy',
              'rnn_bidirectional': False,
              'rnn_dropout': 0.0,
              'rnn_hidden_size': 1024,
              'rnn_num_layers': 2,
              'text_embed_size': 32,
              'translation_aug': { 'network': 'TranslationAug',
                                   'network_kwargs': { 'input_shape': None,
                                                       'translation': 8}}},
  'pretrain': False,
  'pretrain_model_path': '',
  'seed': 0,
  'task_embedding_format': 'bert',
  'task_embedding_one_hot_offset': 1,
  'train': { 'batch_size': 48,
             'debug': False,
             'grad_clip': 100.0,
             'loss_scale': 1.0,
             'n_epochs': 50,
             'num_workers': 2,
             'optimizer': { 'kwargs': { 'betas': [0.9, 0.999],
                                        'lr': 0.0001,
                                        'weight_decay': 0.0001},
                            'name': 'torch.optim.AdamW'},
             'resume': False,
             'resume_path': '',
             'scheduler': { 'kwargs': {'eta_min': 1e-05, 'last_epoch': -1},
                            'name': 'torch.optim.lr_scheduler.CosineAnnealingLR'},
             'use_augmentation': True},
  'use_wandb': False,
  'wandb_project': 'lifelong learning'}
'Available algorithms:'
{ 'agem': <class 'libero.lifelong.algos.agem.AGEM'>,
  'er': <class 'libero.lifelong.algos.er.ER'>,
  'ewc': <class 'libero.lifelong.algos.ewc.EWC'>,
  'multitask': <class 'libero.lifelong.algos.multitask.Multitask'>,
  'packnet': <class 'libero.lifelong.algos.packnet.PackNet'>,
  'sequential': <class 'libero.lifelong.algos.base.Sequential'>,
  'singletask': <class 'libero.lifelong.algos.single_task.SingleTask'>}
'Available policies:'
{ 'bcrnnpolicy': <class 'libero.lifelong.models.bc_rnn_policy.BCRNNPolicy'>,
  'bctransformerpolicy': <class 'libero.lifelong.models.bc_transformer_policy.BCTransformerPolicy'>,
  'bcviltpolicy': <class 'libero.lifelong.models.bc_vilt_policy.BCViLTPolicy'>}
[info] using task orders [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

============= Initialized Observation Utils with Obs Spec =============

using obs modality: rgb with keys: ['eye_in_hand_rgb', 'agentview_rgb']
using obs modality: depth with keys: []
using obs modality: low_dim with keys: ['joint_states', 'gripper_states']
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 302.53it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_alphabet_soup_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 318.71it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_cream_cheese_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 312.77it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_salad_dressing_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 318.38it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_bbq_sauce_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 299.41it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_ketchup_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 314.74it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_tomato_sauce_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 304.23it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_butter_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 327.94it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_milk_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 295.45it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_chocolate_pudding_and_place_it_in_the_basket_demo.hdf5
SequenceDataset: loading dataset into memory...
100%|??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????| 50/50 [00:00<00:00, 326.11it/s]
/home/lyf/Videos/bin/boot/LIBERO/datasets/libero_object/pick_up_the_orange_juice_and_place_it_in_the_basket_demo.hdf5

=================== Lifelong Benchmark Information  ===================
 Name: libero_object
 # Tasks: 10
    - Task 1:
        pick up the alphabet soup and place it in the basket
    - Task 2:
        pick up the cream cheese and place it in the basket
    - Task 3:
        pick up the salad dressing and place it in the basket
    - Task 4:
        pick up the bbq sauce and place it in the basket
    - Task 5:
        pick up the ketchup and place it in the basket
    - Task 6:
        pick up the tomato sauce and place it in the basket
    - Task 7:
        pick up the butter and place it in the basket
    - Task 8:
        pick up the milk and place it in the basket
    - Task 9:
        pick up the chocolate pudding and place it in the basket
    - Task 10:
        pick up the orange juice and place it in the basket
 # demonstrations: (50) (50) (50) (50) (50) (50) (50) (50) (50) (50)
 # sequences: (7808) (7194) (6641) (7348) (8056) (7364) (7865) (7281) (7982) (6968)
=======================================================================

[info] start lifelong learning with algo Sequential
[info] policy has 13.5 GFLOPs and 19.1 MParams

[info] start training on task 0
Error executing job with overrides: ['seed=0', 'benchmark_name=libero_object', 'policy=bc_rnn_policy', 'lifelong=base']
Traceback (most recent call last):
  File "lifelong/main.py", line 223, in main
    s_fwd, l_fwd = algo.learn_one_task(
  File "/home/lyf/Videos/bin/boot/LIBERO/libero/lifelong/algos/base.py", line 175, in learn_one_task
    for (idx, data) in enumerate(train_dataloader):
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 439, in __iter__
    return self._get_iterator()
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/lyf/anaconda3/envs/LIBERO/lib/python3.8/site-packages/h5py/_hl/base.py", line 368, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

**Comment by raymondyu5** [comment]
Hi, I am also receiving this problem when I run:
```
export CUDA_VISIBLE_DEVICES=0 && export MUJOCO_EGL_DEVICE_ID=0 && python lifelong/main.py seed=0 benchmark_name=libero_90 policy=bc_rnn_policy lifelong=base
```
I receive this:
```
=================== Lifelong Benchmark Information  ===================
 Name: libero_90
 # Tasks: 90
    - Task 1:
        close the top drawer of the cabinet
    - Task 2:
        close the top drawer of the cabinet and put the black bowl on top of it
    - Task 3:
        put the black bowl in the top drawer of the cabinet
    - Task 4:
        put the butter at the back in the top drawer of the cabinet and close it
    - Task 5:
        put the butter at the front in the top drawer of the cabinet and close it
    - Task 6:
        put the chocolate pudding in the top drawer of the cabinet and close it
    - Task 7:
        open the bottom drawer of the cabinet
    - Task 8:
        open the top drawer of the cabinet
    - Task 9:
        open the top drawer of the cabinet and put the bowl in it
    - Task 10:
        put the black bowl on the plate
    - Task 11:
        put the black bowl on top of the cabinet
    - Task 12:
        open the top drawer of the cabinet
    - Task 13:
        put the black bowl at the back on the plate
    - Task 14:
        put the black bowl at the front on the plate
    - Task 15:
        put the middle black bowl on the plate
    - Task 16:
        put the middle black bowl on top of the cabinet
    - Task 17:
        stack the black bowl at the front on the black bowl in the middle
    - Task 18:
        stack the middle black bowl on the back black bowl
    - Task 19:
        put the frying pan on the stove
    - Task 20:
        put the moka pot on the stove
    - Task 21:
        turn on the stove
    - Task 22:
        turn on the stove and put the frying pan on it
    - Task 23:
        close the bottom drawer of the cabinet
    - Task 24:
        close the bottom drawer of the cabinet and open the top drawer
    - Task 25:
        put the black bowl in the bottom drawer of the cabinet
    - Task 26:
        put the black bowl on top of the cabinet
    - Task 27:
        put the wine bottle in the bottom drawer of the cabinet
    - Task 28:
        put the wine bottle on the wine rack
    - Task 29:
        close the top drawer of the cabinet
    - Task 30:
        put the black bowl in the top drawer of the cabinet
    - Task 31:
        put the black bowl on the plate
    - Task 32:
        put the black bowl on top of the cabinet
    - Task 33:
        put the ketchup in the top drawer of the cabinet
    - Task 34:
        close the microwave
    - Task 35:
        put the yellow and white mug to the front of the white mug
    - Task 36:
        open the microwave
    - Task 37:
        put the white bowl on the plate
    - Task 38:
        put the white bowl to the right of the plate
    - Task 39:
        put the right moka pot on the stove
    - Task 40:
        turn off the stove
    - Task 41:
        put the frying pan on the cabinet shelf
    - Task 42:
        put the frying pan on top of the cabinet
    - Task 43:
        put the frying pan under the cabinet shelf
    - Task 44:
        put the white bowl on top of the cabinet
    - Task 45:
        turn on the stove
    - Task 46:
        turn on the stove and put the frying pan on it
    - Task 47:
        pick up the alphabet soup and put it in the basket
    - Task 48:
        pick up the cream cheese box and put it in the basket
    - Task 49:
        pick up the ketchup and put it in the basket
    - Task 50:
        pick up the tomato sauce and put it in the basket
    - Task 51:
        pick up the alphabet soup and put it in the basket
    - Task 52:
        pick up the butter and put it in the basket
    - Task 53:
        pick up the milk and put it in the basket
    - Task 54:
        pick up the orange juice and put it in the basket
    - Task 55:
        pick up the tomato sauce and put it in the basket
    - Task 56:
        pick up the alphabet soup and put it in the tray
    - Task 57:
        pick up the butter and put it in the tray
    - Task 58:
        pick up the cream cheese and put it in the tray
    - Task 59:
        pick up the ketchup and put it in the tray
    - Task 60:
        pick up the tomato sauce and put it in the tray
    - Task 61:
        pick up the black bowl on the left and put it in the tray
    - Task 62:
        pick up the chocolate pudding and put it in the tray
    - Task 63:
        pick up the salad dressing and put it in the tray
    - Task 64:
        stack the left bowl on the right bowl and place them in the tray
    - Task 65:
        stack the right bowl on the left bowl and place them in the tray
    - Task 66:
        put the red mug on the left plate
    - Task 67:
        put the red mug on the right plate
    - Task 68:
        put the white mug on the left plate
    - Task 69:
        put the yellow and white mug on the right plate
    - Task 70:
        put the chocolate pudding to the left of the plate
    - Task 71:
        put the chocolate pudding to the right of the plate
    - Task 72:
        put the red mug on the plate
    - Task 73:
        put the white mug on the plate
    - Task 74:
        pick up the book and place it in the front compartment of the caddy
    - Task 75:
        pick up the book and place it in the left compartment of the caddy
    - Task 76:
        pick up the book and place it in the right compartment of the caddy
    - Task 77:
        pick up the yellow and white mug and place it to the right of the caddy
    - Task 78:
        pick up the book and place it in the back compartment of the caddy
    - Task 79:
        pick up the book and place it in the front compartment of the caddy
    - Task 80:
        pick up the book and place it in the left compartment of the caddy
    - Task 81:
        pick up the book and place it in the right compartment of the caddy
    - Task 82:
        pick up the book and place it in the front compartment of the caddy
    - Task 83:
        pick up the book and place it in the left compartment of the caddy
    - Task 84:
        pick up the book and place it in the right compartment of the caddy
    - Task 85:
        pick up the red mug and place it to the right of the caddy
    - Task 86:
        pick up the white mug and place it to the right of the caddy
    - Task 87:
        pick up the book in the middle and place it on the cabinet shelf
    - Task 88:
        pick up the book on the left and place it on top of the shelf
    - Task 89:
        pick up the book on the right and place it on the cabinet shelf
    - Task 90:
        pick up the book on the right and place it under the cabinet shelf
 # demonstrations: (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50) (50)
 # sequences: (3828) (10662) (6208) (9440) (9070) (8969) (7157) (4736) (10010) (6628) (6811) (3765) (5538) (6910) (5393) (6821) (6415) (5730) (9979) (7563) (4645) (14013) (5832) (11773) (6643) (7910) (6376) (12093) (3762) (6107) (6665) (7576) (10539) (10160) (6282) (7414) (9702) (6946) (10588) (8795) (9457) (9272) (8612) (7519) (5871) (13047) (6939) (7426) (8665) (8088) (7034) (6609) (5875) (8383) (5306) (6004) (5069) (7697) (7986) (5571) (6176) (7660) (5970) (10771) (11734) (7239) (7032) (5327) (5377) (6195) (4473) (6668) (7907) (8742) (7938) (7831) (6405) (7336) (7582) (6104) (7115) (8738) (7310) (6774) (5896) (5158) (8055) (8547) (5111) (5988)
=======================================================================

/home/raymond/anaconda3/envs/libero/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
[info] start lifelong learning with algo Sequential
/home/raymond/anaconda3/envs/libero/lib/python3.8/site-packages/robomimic/utils/dataset.py:516: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  pad_mask = pad_mask[:, None].astype(np.bool)
/home/raymond/anaconda3/envs/libero/lib/python3.8/site-packages/torch/nn/modules/rnn.py:761: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at  ../aten/src/ATen/native/cudnn/RNN.cpp:926.)
  result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
[info] policy has 13.5 GFLOPs and 19.1 MParams

[info] start training on task 0
Error executing job with overrides: ['seed=0', 'benchmark_name=libero_90', 'policy=bc_rnn_policy', 'lifelong=base']
Traceback (most recent call last):
  File "lifelong/main.py", line 219, in main
    s_fwd, l_fwd = algo.learn_one_task(
  File "/home/raymond/LIBERO/libero/lifelong/algos/base.py", line 175, in learn_one_task
    for (idx, data) in enumerate(train_dataloader):
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 363, in __iter__
    self._iterator = self._get_iterator()
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 927, in __init__
    w.start()
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/raymond/anaconda3/envs/libero/lib/python3.8/site-packages/h5py/_hl/base.py", line 370, in __getnewargs__
    raise TypeError("h5py objects cannot be pickled")
TypeError: h5py objects cannot be pickled

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
Please let me know, thanks!

**Comment by bit0123** [comment]
Hi @Cranial-XIX 
Thanks for the interesting paper and releasing the code.
I am facing the same issue ("TypeError: h5py objects cannot be pickled") while running with num_worker=4. Although the code works with num_worker=0 with some additional transformation of image input in the policy file, The loss becomes negative after the first epoch for different algorithm. Consequently, the accuracy is 0. 
Could you please comment on that.
Thanks

**Comment by modanesh** [comment]
@Cranial-XIX Any solutions?

**Comment by modanesh** [comment]
Tried all configurations of `algo`, `policy`, and `benchmark` and still got the same error.

**Comment by raymondyu5** [comment]
Try adding these two lines to venv.py. This took me like two days to figure out, so I hope this helps!
if multiprocessing.get_start_method(allow_none=True) != "spawn":  
    multiprocessing.set_start_method("spawn", force=True)

**Comment by modanesh** [comment]
@raymondyu5 Thanks for the response. Where should I exactly add these lines?

Btw, from my understanding, `venv.py` file is not used when running the training (`libero/lifelong/main.py`) which is what I want to do.

**Comment by bit0123** [comment]
Hi @BrightMoonStar and @raymondyu5 
Could you please comment on the following observation. 
"The code works with num_worker=0, however the loss becomes negative after the first epoch for different algorithm. Consequently, succes and the AoC is 0."
Thanks for your response.

**Comment by wangair** [comment]
Hi!
I met the same problem.I set num_worker=0, but it didn't work for me. When i set:
`num_worker=0`
I received this:
> ValueError: persistent_workers option needs num_workers > 0
How can i solve this error?Thank you very much.

**Comment by BrightMoonStar** [comment]
> 你好@BrightMoonStar，@raymondyu5和@Cranial-XIX 您能否使用 ER 算法对以下观察进行评论。 “代码在 num_worker=0 的情况下有效，但是对于不同的算法，在第一个 epoch 之后损失变为负值。因此，成功且 AoC 为 0。” 感谢您的回复。

I meet the same problem

**Comment by BrightMoonStar** [comment]
> 你好@BrightMoonStar，@raymondyu5和@Cranial-XIX 您能否使用 ER 算法对以下观察进行评论。 “代码在 num_worker=0 的情况下有效，但是对于不同的算法，在第一个 epoch 之后损失变为负值。因此，成功且 AoC 为 0。” 感谢您的回复。

Have you solved it？Thanks for your reply!

**Comment by pengzhi1998** [comment]
Dear all,

I faced the same issue. And I found here a solution: https://github.com/pytorch/pytorch/issues/11929 and https://discuss.pytorch.org/t/hdf5-multi-threaded-alternative/6189/9. They both mentioned we need to open the hdf5 file in `__getitem__` method but not `__init__` of the custom `Dataset` if using multi-processing dataloader. Thus, I modified directly on [SequenceDataset from RoboMimic](https://github.com/ARISE-Initiative/robomimic/blob/v0.3.0/robomimic/utils/dataset.py#L18). However, the problem of "TypeError: h5py objects cannot be pickled" still exists. Have you solved this issue?

May I have your suggestions on this? @Cranial-XIX @zhuyifengzju 

Thank you for your attention on this matter and for your precious time!!

Best regards,
Pengzhi

**Comment by pengzhi1998** [comment]
> Hi! I met the same problem.I set num_worker=0, but it didn't work for me. How can i solve this error?Thank you very much.When i set: `num_worker=0` I received this:
> 
> > ValueError: persistent_workers option needs num_workers > 0

Hi, I commented two lines when creating the dataloader in base.py:
```
        train_dataloader = DataLoader(
            dataset,
            batch_size=self.cfg.train.batch_size,
            # num_workers=self.cfg.train.num_workers,
            sampler=RandomSampler(dataset),
            # persistent_workers=False,
        )
```

**Comment by Cranial-XIX** [comment]
Hi, May I ask if you are using a Linux or Windows machine to run it?

**Comment by Cranial-XIX** [comment]
Can you comment the

```
if multiprocessing.get_start_method(allow_none=True) != "spawn":
    multiprocessing.set_start_method("spawn", force=True) 
```

From 270-271 in `libero/lifelong/main.py` and try again?

**Comment by pengzhi1998** [comment]
Thank you so much for your reply!

Your solution worked! However, if I comment out the two lines, the issue reappears (https://github.com/Lifelong-Robot-Learning/LIBERO/issues/3).

I would first try downgrading the Cuda/Driver version. Besides this method, may I have your suggestions on this?

Thank you so much again. Look forward to your reply!

**Comment by Junxix** [comment]
> Can you comment the
> 
> ```
> if multiprocessing.get_start_method(allow_none=True) != "spawn":
>     multiprocessing.set_start_method("spawn", force=True) 
> ```
> 
> From 270-271 in `libero/lifelong/main.py` and try again? Try keeping everything else the same as in the HEAD first. It works fine on my side.

I still get the same problem after adding the two lines. Do you know how to solve it?

**Comment by Kami-code** [comment]
I have encountered the same problem on my 3.10 environment.

For my 3.8 environment, I don't have to do any modification and it works. 
For the 3.10 environment, I commented the 

`if multiprocessing.get_start_method(allow_none=True) != "spawn":
    multiprocessing.set_start_method("spawn", force=True) `

and it starts training.

**Comment by Twilighthui** [comment]
I meet the same issue. I solve this in libero/lifelong/main.py by:
```
if __name__ == "__main__":
    # Set the multiprocessing start method from 'spawn' to 'fork'
    if multiprocessing.get_start_method(allow_none=True) != "fork":  
        multiprocessing.set_start_method("fork", force=True)
    main()
```
Hope this can help you.

**Comment by zsc0731** [comment]
it's really helpful:(changing the base.py)
train_dataloader = DataLoader(
            dataset,
            batch_size=self.cfg.train.batch_size,
            num_workers=0,                # 0
            sampler=RandomSampler(dataset),
            persistent_workers=False      # False
        )
